CREATE TABLE bookings (
    booking_id VARCHAR(50),
    user_id VARCHAR(50),
    venue_id VARCHAR(50),
    booking_date DATE,
    booking_time TIME,
    sport VARCHAR(50),
    city VARCHAR(100),
    area VARCHAR(100),
    venue_name VARCHAR(150),
    court_type VARCHAR(100),
    duration_hours INT,
    players_count INT,
    booking_amount INT,
    discount INT,
    final_amount INT,
    payment_method VARCHAR(50),
    booking_status VARCHAR(50),
    cancellation_reason VARCHAR(150),
    booking_source VARCHAR(50),
    booking_lead_days INT,
    rating NUMERIC,
    booking_hour INT,
    day_type VARCHAR(20),
    month VARCHAR(20),
    weekday VARCHAR(20),
    is_cancelled INT
);
--check the total rows
select count(*) 
from bookings;

-- check the imported data 
select * from bookings 
limit 10 ;

--checking the unique users and venues 
SELECT COUNT(DISTINCT user_id) AS total_users
FROM bookings;
SELECT COUNT(DISTINCT venue_id) AS total_venues
FROM bookings;

--Check duplicate bookings
SELECT
    booking_id,
    COUNT(*) AS occurrence
FROM bookings
GROUP BY booking_id
HAVING COUNT(*) > 1;

--Check missing values
--Booking ID
SELECT COUNT(*) AS missing_booking_id
FROM bookings
WHERE booking_id IS NULL;
--User ID
SELECT COUNT(*) AS missing_user_id
FROM bookings
WHERE user_id IS NULL;
--Sport
SELECT COUNT(*) AS missing_sport
FROM bookings
WHERE sport IS NULL;
--Final amount
SELECT COUNT(*) AS missing_final_amount
FROM bookings
WHERE final_amount IS NULL;

---Check categorical values
--Booking status
SELECT booking_status,COUNT(*) AS total
FROM bookings
GROUP BY booking_status
ORDER BY total DESC;
--Sports
SELECT sport,COUNT(*) AS total_bookings
FROM bookings
GROUP BY sport
ORDER BY total_bookings DESC;
---Check dates and numerical values
--Date range
SELECT MIN(booking_date) AS earliest_booking,MAX(booking_date) AS latest_booking
FROM bookings;
--Booking amount
SELECT MIN(final_amount) AS minimum_amount,MAX(final_amount) AS maximum_amount,AVG(final_amount) AS average_amount
FROM bookings;
--Players
SELECT MIN(players_count) AS minimum_players,MAX(players_count) AS maximum_players,AVG(players_count) AS average_players
FROM bookings;


---BASIC KPI'S
--total bookings 
select count(*) from bookings ;
-- total users 
select count(distinct(user_id)) from bookings;
--total venues 
select count(distinct(venue_id)) from bookings;
--total revenue 
select sum(final_amount)from bookings;
--average booking value 
select avg(final_amount) from bookings ;
--cancellation rate 
select round(100.0*sum(is_cancelled)/count(*), 2) as cencellation_rate from bookings;
--cancelled revenue 
select sum(final_amount) from bookings
where is_cancelled = 1; 
--average players per booking 
select round(avg(players_count) , 2) from bookings;
--avg booking durations 
select round(avg(duration_hours), 2) from bookings;
--repeated users 
SELECT
    ROUND(
        100.0 *
        COUNT(*) FILTER (
            WHERE booking_count > 1
        )
        / COUNT(*),
        2
    ) AS repeat_user_rate
FROM (
    SELECT
        user_id,
        COUNT(*) AS booking_count
    FROM bookings
    GROUP BY user_id
) AS user_booking_counts;


---Sport Analysis
--Number of bookings by sport
SELECT
    sport,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY sport
ORDER BY total_bookings DESC;
--Revenue by sport
SELECT
    sport,
    SUM(final_amount) AS total_revenue
FROM bookings
GROUP BY sport
ORDER BY total_revenue DESC;

--Average booking value by sport
SELECT
    sport,
    ROUND(AVG(final_amount), 2) AS average_booking_value
FROM bookings
GROUP BY sport
ORDER BY average_booking_value DESC;

--Cancellation rate by sport
SELECT
    sport,
    ROUND(
        100.0 * AVG(is_cancelled),
        2
    ) AS cancellation_rate
FROM bookings
GROUP BY sport
ORDER BY cancellation_rate DESC;

--Sport × booking hour
SELECT
    sport,
    booking_hour,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY sport, booking_hour
ORDER BY total_bookings DESC;

-- Number of bookings by venue
SELECT
    venue_name,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY venue_name
ORDER BY total_bookings DESC;

--Top 10 venues by bookings
SELECT
    venue_name,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY venue_name
ORDER BY total_bookings DESC
LIMIT 10;

--Revenue generated by each venue
SELECT
    venue_name,
    SUM(final_amount) AS total_revenue
FROM bookings
GROUP BY venue_name
ORDER BY total_revenue DESC;

--Average booking value by venue
SELECT
    venue_name,
    ROUND(AVG(final_amount), 2) AS average_booking_value
FROM bookings
GROUP BY venue_name
ORDER BY average_booking_value DESC;

--Cancellation rate by venue
SELECT
    venue_name,
    ROUND(
        100.0 * AVG(is_cancelled),
        2
    ) AS cancellation_rate
FROM bookings
GROUP BY venue_name
ORDER BY cancellation_rate DESC;

---Location analysis 
--Bookings by city
SELECT
    city,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY city
ORDER BY total_bookings DESC;

--  Revenue by city
SELECT
    city,
    SUM(final_amount) AS total_revenue
FROM bookings
GROUP BY city
ORDER BY total_revenue DESC;

--Bookings by area
SELECT
    area,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY area
ORDER BY total_bookings DESC;

--top 10 area 
SELECT
    area,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY area
ORDER BY total_bookings DESC
LIMIT 10;

--city + area 
SELECT
    city,
    area,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY city, area
ORDER BY total_bookings DESC;

--avg value by city 
SELECT
    city,
    ROUND(AVG(final_amount), 2) AS average_booking_value
FROM bookings
GROUP BY city
ORDER BY average_booking_value DESC;

--User Analysis 
--Bookings per user
SELECT
    user_id,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY user_id
ORDER BY total_bookings DESC;

--Identify repeat users
SELECT
    user_id,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY user_id
HAVING COUNT(*) > 1
ORDER BY total_bookings DESC;

--Count repeat users
SELECT
    COUNT(*) AS repeat_users
FROM (
    SELECT
        user_id
    FROM bookings
    GROUP BY user_id
    HAVING COUNT(*) > 1
) AS repeat_user_list;

--One-time users
SELECT
    COUNT(*) AS one_time_users
FROM (
    SELECT
        user_id
    FROM bookings
    GROUP BY user_id
    HAVING COUNT(*) = 1
) AS one_time_user_list;

-- Revenue from repeat users
SELECT
    SUM(final_amount) AS repeat_user_revenue
FROM bookings
WHERE user_id IN (
    SELECT
        user_id
    FROM bookings
    GROUP BY user_id
    HAVING COUNT(*) > 1
);

--Average bookings per user
SELECT
    ROUND(
        COUNT(*)::NUMERIC / COUNT(DISTINCT user_id),
        2
    ) AS average_bookings_per_user
FROM bookings;

--Cancellation Analysis
-- Total cancelled bookings
SELECT
    COUNT(*) AS cancelled_bookings
FROM bookings
WHERE is_cancelled = 1;
--Cancellation rate
SELECT
    ROUND(
        100.0 * SUM(is_cancelled) / COUNT(*),
        2
    ) AS cancellation_rate
FROM bookings;
--Cancellation reasons
SELECT
    cancellation_reason,
    COUNT(*) AS cancellations
FROM bookings
WHERE is_cancelled = 1
GROUP BY cancellation_reason
ORDER BY cancellations DESC;
--Cancellation rate by sport
SELECT
    sport,
    ROUND(
        100.0 * AVG(is_cancelled),
        2
    ) AS cancellation_rate
FROM bookings
GROUP BY sport
ORDER BY cancellation_rate DESC;
--Cancellation rate by venue
SELECT
    venue_name,
    ROUND(
        100.0 * AVG(is_cancelled),
        2
    ) AS cancellation_rate
FROM bookings
GROUP BY venue_name
ORDER BY cancellation_rate DESC;
--Cancellation rate by city
SELECT
    city,
    ROUND(
        100.0 * AVG(is_cancelled),
        2
    ) AS cancellation_rate
FROM bookings
GROUP BY city
ORDER BY cancellation_rate DESC;
--Cancellation rate by booking hour
SELECT
    booking_hour,
    ROUND(
        100.0 * AVG(is_cancelled),
        2
    ) AS cancellation_rate
FROM bookings
GROUP BY booking_hour
ORDER BY cancellation_rate DESC;
--Cancellation rate by booking source
SELECT
    booking_source,
    ROUND(
        100.0 * AVG(is_cancelled),
        2
    ) AS cancellation_rate
FROM bookings
GROUP BY booking_source
ORDER BY cancellation_rate DESC;
--Cancellation rate by booking lead days
SELECT
    CASE
        WHEN booking_lead_days = 0 THEN 'Same day'
        WHEN booking_lead_days BETWEEN 1 AND 3 THEN '1-3 days'
        WHEN booking_lead_days BETWEEN 4 AND 7 THEN '4-7 days'
        ELSE '8+ days'
    END AS lead_time_group,
    COUNT(*) AS total_bookings,
    ROUND(
        100.0 * AVG(is_cancelled),
        2
    ) AS cancellation_rate
FROM bookings
GROUP BY lead_time_group
ORDER BY cancellation_rate DESC;

--Revenue Analysis
--Total revenue by sport
SELECT
    sport,
    SUM(final_amount) AS total_revenue
FROM bookings
GROUP BY sport
ORDER BY total_revenue DESC;

--Revenue by venue
SELECT
    venue_name,
    SUM(final_amount) AS total_revenue
FROM bookings
GROUP BY venue_name
ORDER BY total_revenue DESC;

--Revenue by city
SELECT
    city,
    SUM(final_amount) AS total_revenue
FROM bookings
GROUP BY city
ORDER BY total_revenue DESC;

--Revenue by payment method
SELECT
    payment_method,
    COUNT(*) AS total_bookings,
    SUM(final_amount) AS total_revenue
FROM bookings
GROUP BY payment_method
ORDER BY total_revenue DESC;

--Revenue by booking status
SELECT
    booking_status,
    COUNT(*) AS total_bookings,
    SUM(final_amount) AS total_revenue
FROM bookings
GROUP BY booking_status
ORDER BY total_revenue DESC;

--Revenue by booking status
SELECT
    booking_status,
    COUNT(*) AS total_bookings,
    SUM(final_amount) AS total_revenue
FROM bookings
GROUP BY booking_status
ORDER BY total_revenue DESC;

--Revenue by month
SELECT
    month,
    SUM(final_amount) AS total_revenue
FROM bookings
GROUP BY month
ORDER BY total_revenue DESC;

--Discount analysis
SELECT
    SUM(booking_amount) AS gross_booking_value,
    SUM(discount) AS total_discount,
    SUM(final_amount) AS final_booking_value
FROM bookings;

--Average discount by sport
SELECT
    sport,
    ROUND(AVG(discount), 2) AS average_discount
FROM bookings
GROUP BY sport
ORDER BY average_discount DESC;

--Create booking value categories
SELECT
    booking_id,
    final_amount,
    CASE
        WHEN final_amount <= 500 THEN 'Low Value'
        WHEN final_amount <= 1000 THEN 'Medium Value'
        ELSE 'High Value'
    END AS booking_value_category
FROM bookings;

--Count bookings in each category
SELECT
    CASE
        WHEN final_amount <= 500 THEN 'Low Value'
        WHEN final_amount <= 1000 THEN 'Medium Value'
        ELSE 'High Value'
    END AS booking_value_category,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY
    CASE
        WHEN final_amount <= 500 THEN 'Low Value'
        WHEN final_amount <= 1000 THEN 'Medium Value'
        ELSE 'High Value'
    END
ORDER BY total_bookings DESC;

--Categorize users by booking frequency
SELECT
    user_id,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY user_id;
SELECT
    user_id,
    total_bookings,
    CASE
        WHEN total_bookings = 1 THEN 'One-time User'
        WHEN total_bookings BETWEEN 2 AND 5 THEN 'Regular User'
        ELSE 'Frequent User'
    END AS user_category
FROM (
    SELECT
        user_id,
        COUNT(*) AS total_bookings
    FROM bookings
    GROUP BY user_id
) AS user_data;

--Cancellation classification
SELECT
    booking_id,
    booking_status,
    CASE
        WHEN is_cancelled = 1 THEN 'Cancelled'
        ELSE 'Not Cancelled'
    END AS cancellation_category
FROM bookings;

--Calculate cancellation rate using CASE
SELECT
    sport,
    COUNT(*) AS total_bookings,
    SUM(
        CASE
            WHEN is_cancelled = 1 THEN 1
            ELSE 0
        END
    ) AS cancelled_bookings,
    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN is_cancelled = 1 THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS cancellation_rate
FROM bookings
GROUP BY sport
ORDER BY cancellation_rate DESC;

--Bookings above average value
SELECT
    booking_id,
    user_id,
    sport,
    final_amount
FROM bookings
WHERE final_amount > (
    SELECT AVG(final_amount)
    FROM bookings
);
--Venues generating above-average revenue
SELECT
    venue_name,
    SUM(final_amount) AS total_revenue
FROM bookings
GROUP BY venue_name
HAVING SUM(final_amount) > (
    SELECT AVG(venue_revenue)
    FROM (
        SELECT
            venue_name,
            SUM(final_amount) AS venue_revenue
        FROM bookings
        GROUP BY venue_name
    ) AS venue_data
)
ORDER BY total_revenue DESC;
--Users with more bookings than the average user
SELECT
    user_id,
    COUNT(*) AS total_bookings
FROM bookings
GROUP BY user_id
HAVING COUNT(*) > (
    SELECT AVG(user_booking_count)
    FROM (
        SELECT
            user_id,
            COUNT(*) AS user_booking_count
        FROM bookings
        GROUP BY user_id
    ) AS user_counts
)
ORDER BY total_bookings DESC;
--Find the highest-value booking
SELECT *
FROM bookings
WHERE final_amount = (
    SELECT MAX(final_amount)
    FROM bookings
);

--inner joins 
SELECT
    b.booking_id,
    b.user_id,
    b.venue_id
FROM bookings b
INNER JOIN users u
    ON b.user_id = u.user_id;

--LEFT JOIN
SELECT
    b.booking_id,
    b.user_id,
    u.user_name
FROM bookings b
LEFT JOIN users u
    ON b.user_id = u.user_id;

--CTES
WITH venue_revenue AS (
    SELECT
        venue_name,
        SUM(final_amount) AS total_revenue
    FROM bookings
    GROUP BY venue_name
)

SELECT *
FROM venue_revenue
ORDER BY total_revenue DESC;

--Window Functions
--Rank venues by revenue
SELECT
    venue_name,
    SUM(final_amount) AS total_revenue,

    RANK() OVER (
        ORDER BY SUM(final_amount) DESC
    ) AS revenue_rank

FROM bookings
GROUP BY venue_name;
--Rank sports by revenue
SELECT
    sport,
    SUM(final_amount) AS total_revenue,

    RANK() OVER (
        ORDER BY SUM(final_amount) DESC
    ) AS revenue_rank

FROM bookings
GROUP BY sport;
--Rank users by number of bookings
SELECT
    user_id,
    COUNT(*) AS total_bookings,

    RANK() OVER (
        ORDER BY COUNT(*) DESC
    ) AS booking_rank

FROM bookings
GROUP BY user_id;

--ROW_NUMBER()
SELECT
    user_id,
    booking_id,
    booking_date,
    ROW_NUMBER() OVER (
        PARTITION BY user_id
        ORDER BY booking_date
    ) AS booking_number
FROM bookings;

--LAG()
SELECT
    user_id,
    booking_date,
    final_amount,
    LAG(final_amount) OVER (
        PARTITION BY user_id
        ORDER BY booking_date
    ) AS previous_booking_amount
FROM bookings;

--Running Revenue
SELECT
    booking_date,
    final_amount,

    SUM(final_amount) OVER (
        ORDER BY booking_date
    ) AS cumulative_revenue

FROM bookings
ORDER BY booking_date;

--Monthly Revenue + Previous Month Comparison
WITH monthly_revenue AS (
    SELECT
        DATE_TRUNC('month', booking_date) AS month,
        SUM(final_amount) AS revenue
    FROM bookings
    GROUP BY DATE_TRUNC('month', booking_date)
)

SELECT
    month,
    revenue,

    LAG(revenue) OVER (
        ORDER BY month
    ) AS previous_month_revenue

FROM monthly_revenue
ORDER BY month;

--PARTITION BY
SELECT
    user_id,
    booking_date,
    final_amount,

    AVG(final_amount) OVER (
        PARTITION BY user_id
    ) AS user_average_booking_value
FROM bookings;

--Conditional Aggregation
SELECT
    sport,

    COUNT(*) AS total_bookings,

    SUM(
        CASE
            WHEN is_cancelled = 1 THEN 1
            ELSE 0
        END
    ) AS cancelled_bookings,
    SUM(
        CASE
            WHEN is_cancelled = 0 THEN 1
            ELSE 0
        END
    ) AS completed_bookings
FROM bookings
GROUP BY sport;




